APP_NAME = "LANFileTransfer"
APP_VERSION = "0.9 Alpha"

TRANSFER_PORT = 50007
TRANSFER_BUFFER_SIZE = 64 * 1024
SOCKET_TIMEOUT = 30

PROTOCOL_MAGIC = "LANFILETRANSFER"
PROTOCOL_VERSION = 1

DISCOVERY_SERVICE = "_lanfiletransfer._tcp.local."

SECURITY_CODE = ""